language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy benatt/reverseproxy:latest
  - docker tag udagram-api-user benatt/udagram-api-user:latest
  - docker tag udagram-api-feed benatt/udagram-api-feed:latest
  - docker tag udagram-frontend benatt/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push benatt/reverseproxy
  - docker push benatt/udagram-api-user:latest
  - docker push benatt/udagram-api-feed:latest
  - docker push benatt/udagram-frontend:latest
  