apiVersion: v1
kind: Service
metadata:
  name: publicreverseproxy
spec:
  selector:
    app: reverse
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
  # externalIPs:
  #   - 192.168.49.2
